Repository chocoletter-chat/chocoletter-chat, pull requests merged in 2025-01, with the labels that each got.

#3 [SETTING] 몽고DB 세팅
  chat/src/main/java/chocoletter/chat/chat/controller/ChatMessageController.java
  chat/src/main/java/chocoletter/chat/chat/domain/ChatMessage.java
  chat/src/main/java/chocoletter/chat/chat/dto/ChatMessageRequestDto.java
  chat/src/main/java/chocoletter/chat/chat/repository/ChatMessageRepository.java
  chat/src/main/java/chocoletter/chat/chat/service/ChatMessageService.java
  chat/src/main/resources/application-dev.yml
Labels: feat, 준희 :smile:, setting

#7 [FEAT] 웹소켓 & STOMP 연결
  chat/build.gradle
  chat/src/main/java/chocoletter/chat/api/chat/controller/ChatController.java
  chat/src/main/java/chocoletter/chat/api/chat/controller/ChatMessageController.java
  chat/src/main/java/chocoletter/chat/api/chat/domain/ChatMessage.java
  chat/src/main/java/chocoletter/chat/api/chat/dto/request/ChatMessageRequestDto.java
  chat/src/main/java/chocoletter/chat/api/chat/dto/response/ChatMessageResponseDto.java
  chat/src/main/java/chocoletter/chat/api/chat/repository/ChatMessageRepository.java
  chat/src/main/java/chocoletter/chat/api/chat/service/ChatMessageService.java
  chat/src/main/java/chocoletter/chat/common/config/WebSocketConfig.java
Labels: feat, 준희 :smile:

#10 [FEAT] STOMP와 카프카 연결
  chat/docker-compose.yml
  chat/src/main/java/chocoletter/chat/api/chat/controller/ChatController.java
  chat/src/main/java/chocoletter/chat/api/chat/service/ChatMessageConsumer.java
  chat/src/main/java/chocoletter/chat/api/chat/service/ChatMessageProducer.java
  chat/src/main/java/chocoletter/chat/api/chat/service/ChatMessageService.java
  chat/src/main/java/chocoletter/chat/common/config/KafkaConsumerConfig.java
  chat/src/main/resources/application-dev.yml
  chat/src/main/resources/application.yml
Labels: feat, 예슬 :woman:
