Repository chocoletter-chat/chocoletter-chat, pull requests merged in 2025-02, with the labels that each got.

#16 #12 [FIX] CI/CD 스크립트 수정 및 환경 변수 세팅
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  chat/.gitignore
  chat/Dockerfile
  chat/docker-compose.yml
  chat/src/main/resources/application-dev.yml
Labels: feat, 예슬 :woman:

#18 #17 [FIX] CD 스크립트 트리거 수정
  .github/workflows/cd-dev.yml
Labels: fix, 예슬 :woman:

#15 [FEAT] 마지막 채팅 & 안읽은 채팅 개수 조회
  chat/src/main/java/chocoletter/chat/api/chat/controller/ChatRestController.java
  chat/src/main/java/chocoletter/chat/api/chat/dto/response/LastChatMessageResponseDto.java
  chat/src/main/java/chocoletter/chat/api/chat/repository/ChatMessageRepository.java
  chat/src/main/java/chocoletter/chat/api/chat/service/ChatMessageService.java
Labels: feat, 준희 :smile:
